### ISSUE TITLE
database setup code is not given .sql file

### ISSUE THREAD

**Issue by EniyaGanesan** [NAGARAJ08/Dairy-Management-System#1]

**Comment by prathameshjondhale** [comment]
Hello Sir, I am a student studying in 3rd year diploma computer science and engineering. I found your project useful but unfortunately the database file is missing. 

I will be extremely thankful if you could send me the database file to my email id : prathameshjondhale20@gmail.com

In case you are not able to send the file to my email id you can send the file directly over here so that even other students like me will be benefited from your valuable experience.

Thank you.

**Comment by NAGARAJ08** [comment]
Yeah, the thing is I did this Project long back when I was learning DBMS but uploaded it to git recently when I was switching to my new Laptop but at that time I could not find this database file. I have looked into my Drive account and found it now I have uploaded it. Hope it helps.

**Comment by prathameshjondhale** [comment]
Thank you so much sir
